// portal-backend/src/eduwallet/portalEduWalletClient.ts

/**
 * Portal-facing EduWallet adapter.
 *
 * The portal backend keeps its own portal data in PostgreSQL, but all academic
 * records and access checks still come from the EduWallet contracts through
 * the SDK. This file is the boundary between those two worlds.
 */

import { Wallet as PortalWallet } from "ethers";
import { prisma } from "../lib/prisma";

import {
  askForPermission,
  enrollStudent,
  evaluateStudent,
  getStudentWithResult,
  PermissionType,
  verifyPermission,
  type CourseInfo,
  type Evaluation,
} from "eduwallet-sdk";

type EduWalletSdkWallet = Parameters<typeof askForPermission>[0];

export type OnChainPermissionStatus = "none" | "read" | "write";

/**
 * Reads the local demo key map used by portal organizations.
 *
 * In the prototype these keys are generated by the demo bootstrap script and
 * stored in .env. A production version would replace this with proper
 * organization authentication and key management.
 */
function parseWalletMap(): Record<string, string> {
  const raw = process.env.EDUWALLET_ORG_PRIVATE_KEYS;

  if (!raw) {
    throw new Error(
      "Missing EDUWALLET_ORG_PRIVATE_KEYS. Add organization private keys to portal-backend/.env.",
    );
  }

  try {
    return JSON.parse(raw);
  } catch {
    throw new Error("EDUWALLET_ORG_PRIVATE_KEYS must be valid JSON.");
  }
}

/**
 * Resolves the logged-in portal organization to the wallet used for SDK calls.
 *
 * The database stores organization identity and roles. The demo environment
 * supplies the matching EduWallet private key by organization number.
 */
async function getOrganizationWallet(organizationId: string): Promise<EduWalletSdkWallet> {
  const organization = await prisma.organization.findUnique({
    where: { id: organizationId },
  });

  if (!organization) {
    throw new Error("Organization not found.");
  }

  const walletMap = parseWalletMap();
  const privateKey = walletMap[organization.organizationNumber];

  if (!privateKey) {
    throw new Error(
      `No EduWallet private key configured for organization number ${organization.organizationNumber}.`,
    );
  }

  const portalWallet = new PortalWallet(privateKey);

  // The SDK and portal-backend currently resolve ethers from two different node_modules folders.
  // At runtime this is still an ethers Wallet, but TypeScript treats them as incompatible.
  return portalWallet as unknown as EduWalletSdkWallet;
}

/**
 * Creates an on-chain access request from a portal organization to a student.
 *
 * The resulting request is later visible to the student client, where the
 * student can approve View access (read) or Update access (write).
 */
export async function requestOnChainPermission(input: {
  organizationId: string;
  studentSca: string;
  permissionType: "read" | "write";
}) {
  const wallet = await getOrganizationWallet(input.organizationId);

  const permission = input.permissionType === "write" ? PermissionType.Write : PermissionType.Read;

  await askForPermission(wallet, input.studentSca, permission);
}

/**
 * Reads the current on-chain access level for one organization and student.
 *
 * This deliberately returns the current contract state, not the portal
 * request-log status. The two are kept separate in the portal services.
 */
export async function getOnChainPermissionStatus(input: {
  organizationId: string;
  studentSca: string;
}): Promise<OnChainPermissionStatus> {
  const wallet = await getOrganizationWallet(input.organizationId);

  const permission = await verifyPermission(wallet, input.studentSca);

  if (permission === PermissionType.Write) return "write";
  if (permission === PermissionType.Read) return "read";

  return "none";
}

/**
 * Reads the student's academic record through the organization wallet.
 * The underlying contracts enforce whether the organization can read it.
 */
export async function readOnChainStudent(input: { organizationId: string; studentSca: string }) {
  const wallet = await getOrganizationWallet(input.organizationId);

  return getStudentWithResult(wallet, input.studentSca);
}

/**
 * Issues or updates an academic result on the student's EduWallet account.
 *
 * The portal requires Update access before calling this. If the course is not
 * already enrolled, the prototype enrolls it before writing the evaluation.
 */
export async function submitOnChainCourseResult(input: {
  organizationId: string;
  studentSca: string;
  courseCode: string;
  courseName: string;
  degreeCourse?: string | null;
  ects: string;
  grade: string;
  evaluationDate: string;
}) {
  const wallet = await getOrganizationWallet(input.organizationId);

  const permission = await verifyPermission(wallet, input.studentSca);

  if (permission !== PermissionType.Write) {
    throw new Error("Organization does not have write access for this student.");
  }

  const student = await getStudentWithResult(wallet, input.studentSca);

  type EduWalletAcademicResult = {
    code: string;
    name?: string;
    grade?: string;
    evaluationDate?: string;
    ects?: number;
  };

  const results = (student as { results?: EduWalletAcademicResult[] }).results ?? [];

  const courseAlreadyExists = results.some(
    (result: EduWalletAcademicResult) => result.code === input.courseCode,
  );

  if (!courseAlreadyExists) {
    const course: CourseInfo = {
      code: input.courseCode,
      name: input.courseName,
      degreeCourse: input.degreeCourse ?? "Unknown degree",
      ects: Number(input.ects),
    };

    await enrollStudent(wallet, input.studentSca, [course]);
  }

  const evaluation: Evaluation = {
    code: input.courseCode,
    grade: input.grade,
    evaluationDate: input.evaluationDate,
  };

  await evaluateStudent(wallet, input.studentSca, [evaluation]);

  return getStudentWithResult(wallet, input.studentSca);
}
